name: audio_tts_service_websockets
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  web_socket_channel: ^2.4.0
  record: ^6.0.0
  audioplayers: ^6.4.0
  path_provider: ^2.1.1
  # base64: ^2.3.3
  http: ^1.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true